services:
  ai-agent-olympics:
    networks:
      - n8n_default

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=n8n_default"
      - "traefik.http.routers.ai-agent-olympics.entrypoints=web,websecure"
      - "traefik.http.routers.ai-agent-olympics.rule=Host(`ai-agent-olympics.srv1965124.hstgr.cloud`)"
      - "traefik.http.routers.ai-agent-olympics.tls=true"
      - "traefik.http.routers.ai-agent-olympics.tls.certresolver=mytlschallenge"
      - "traefik.http.services.ai-agent-olympics.loadbalancer.server.port=8501"

networks:
  n8n_default:
    external: true
